// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeJUThvalf9D5tx_fCto_9VQELpcWFq7g',
    appId: '1:561223435401:web:7ec5b27a9c9dfe7f773258',
    messagingSenderId: '561223435401',
    projectId: 'curdop-39fde',
    authDomain: 'curdop-39fde.firebaseapp.com',
    storageBucket: 'curdop-39fde.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARtBYCqhbCs0PAIjr8FEfBQK506THX_sw',
    appId: '1:561223435401:android:fb39688d503546ff773258',
    messagingSenderId: '561223435401',
    projectId: 'curdop-39fde',
    storageBucket: 'curdop-39fde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8_KPsd_-bFQecMJMY4_oK66E8T427gGM',
    appId: '1:561223435401:ios:5fc7f81b537a9ef2773258',
    messagingSenderId: '561223435401',
    projectId: 'curdop-39fde',
    storageBucket: 'curdop-39fde.appspot.com',
    iosBundleId: 'com.example.financialVista',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8_KPsd_-bFQecMJMY4_oK66E8T427gGM',
    appId: '1:561223435401:ios:5fc7f81b537a9ef2773258',
    messagingSenderId: '561223435401',
    projectId: 'curdop-39fde',
    storageBucket: 'curdop-39fde.appspot.com',
    iosBundleId: 'com.example.financialVista',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeJUThvalf9D5tx_fCto_9VQELpcWFq7g',
    appId: '1:561223435401:web:6b12d3d8191662cb773258',
    messagingSenderId: '561223435401',
    projectId: 'curdop-39fde',
    authDomain: 'curdop-39fde.firebaseapp.com',
    storageBucket: 'curdop-39fde.appspot.com',
  );
}
